Repository Normation/rudder-doc, pull requests merged in 2019-11, with the labels that each got.

#626 Fixes #15974: document purging of logs
  src/reference/modules/administration/pages/procedures.adoc
Labels: qa: Can't merge

#631 Fixes #16163: Document the need for systemd for some distributions
  src/reference/modules/installation/pages/operating_systems.adoc
Labels: qa: Can't merge

#634 Fixes #14633: typo in link to generic method mustache introduced in #14446
  src/reference/modules/plugins/pages/windows.adoc
Labels: qa: Can't merge

#639 Fixes #14632: Debian/Ubuntu install doc fails if lsb_release is not installed
  src/reference/modules/installation/pages/_partials/debian_repo.adoc
Labels: qa: Can't merge

#638 Fixes #15271: Backup procedure documentation is incorrect
  src/reference/modules/administration/pages/procedures.adoc
Labels: qa: Can't merge

#640 Fixes #16202: Document new reporting protocol
  src/reference/modules/installation/pages/upgrade.adoc
Labels: Ready for merge

#644 Fixes #16224: Missing documentation on openssl incompatibilities between 4.x and 5.0
  src/reference/modules/installation/pages/upgrade.adoc
Labels: Ready for merge, qa: Can't merge

#586 Fixes #15116: Document use G1GC to better deal with high volume of nodes and reports
  src/reference/modules/administration/pages/performance.adoc
Labels: Ready for merge, qa: Can't merge

#643 Fixes #16217: relayd admin guide
  src/reference/modules/administration/pages/relayd.adoc
Labels: qa: Can't merge

#646 Fixes #16284: Document reporting protocol options
  src/reference/modules/administration/pages/server.adoc
  src/reference/modules/installation/pages/upgrade.adoc
Labels: Ready for merge, qa: Can't merge
