Repository Normation/rudder-doc, pull requests merged in 2019-12, with the labels that each got.

#647 Fixes #16300: Render release notes in the changelog
  src/changelogs/Makefile
Labels: qa: Can't merge

#649 Fixes #16312: Parent broke <6.0 changelogs
  src/changelogs/Makefile
Labels: Ready for merge

#653 Fixes #16375: 6.0 release in docs
  rudder-theme/src/partials/navigation-explore.hbs
  src/get-started/modules/ROOT/pages/home.adoc
Labels: Ready for merge

#655 Fixes #16451: Warn user about know bug in 6.0.1 and installation workaround
  src/reference/modules/installation/nav.adoc.src
  src/reference/modules/installation/pages/install_notes.adoc
Labels: Ready for merge, qa: Can't merge
