Repository Normation/rudder-doc, pull requests merged in 2020-05, with the labels that each got.

#711 Fixes #17299: Doc about missing uuid.hive at upgrade was not upmerged
  src/reference/modules/installation/pages/upgrade.adoc
Labels: Ready for merge, qa: Can't merge

#714 Fixes #17352: improve documentation on "default" for variable to state that it should be quoted
  src/reference/modules/reference/assets/images/group-properties.png
  src/reference/modules/reference/assets/images/group-property-conflict.png
  src/reference/modules/reference/assets/images/node-properties-hierarchy.odg
  src/reference/modules/reference/assets/images/node-properties-hierarchy.png
  src/reference/modules/reference/assets/images/node-properties.png
  src/reference/modules/reference/assets/images/solving-group-conflict-with-subgroup.png
  src/reference/modules/reference/assets/images/solving-hierarchies-conflict-with-subgroup.png
  src/reference/modules/reference/pages/variables.adoc
Labels: qa: Can't merge

#717 Fixes #17369: Typo in merge policy doc
  src/reference/modules/usage/pages/advanced_configuration_management.adoc
  src/reference/modules/usage/pages/variables.adoc
Labels: qa: Can't merge

#718 Fixes #17353: Small fixes in variables page
  src/reference/modules/usage/assets/images/define-subgroup-criteria.png
  src/reference/modules/usage/assets/images/generic-method-result-class.png
  src/reference/modules/usage/assets/images/group-properties.png
  src/reference/modules/usage/assets/images/group-property-conflict.png
  src/reference/modules/usage/assets/images/node-properties-hierarchy.png
  src/reference/modules/usage/assets/images/node-properties.png
  src/reference/modules/usage/assets/images/solving-group-conflict-with-subgroup.png
  src/reference/modules/usage/assets/images/solving-hierarchies-conflict-with-subgroup.png
  src/reference/modules/usage/assets/images/variable-iterator-example.png
  src/reference/modules/usage/assets/images/view-property-inheritance.png
  src/reference/modules/usage/pages/variables.adoc
Labels: Ready for merge, qa: Can't merge

#719 Fixes #17389: Broken links in docs
  src/reference/modules/usage/pages/variables.adoc
Labels: Ready for merge

#720 Fixes #17404: Broken formatting in parent
  src/reference/modules/installation/pages/upgrade.adoc
Labels: Ready for merge, qa: Can't merge
