Repository Normation/rudder-doc, pull requests merged in 2020-11, with the labels that each got.

#799 Fixes #18467: Correct documentation about arrray merge for node properties
  src/reference/modules/usage/pages/variables.adoc
Labels: Ready for merge, Trigger test, qa: Can't merge

#802 Fixes #18532: Improve documentation on disk space requirement
  src/reference/modules/installation/pages/requirements.adoc
Labels: qa: Can't merge

#809 Fixes #18707: Add documentation about set-force-audit in audit/enforce chapter
  src/reference/modules/usage/pages/configuration_management.adoc
Labels: Trigger test, qa: Can't merge
