Repository Normation/rudder-doc, pull requests merged in 2020-07, with the labels that each got.

#759 Fixes #17865: Add docs about configuration-repository, how to sync it and what can be modified or not from outside
  src/reference/modules/administration/pages/security.adoc
  src/reference/modules/administration/pages/server.adoc
Labels: Ready for merge, qa: Can't merge

#757 Fixes #17858: Add a Rudder by example for using Rudder server/relays as file mirror (for repos)
  src/rudder-by-example/modules/ROOT/nav.adoc
  src/rudder-by-example/modules/ROOT/pages/system/file-server-relay.adoc
Labels: Ready for merge, qa: Can't merge

#761 Fixes #17892: Typo in network resiliency documentation
  src/reference/modules/administration/pages/server.adoc
Labels: Ready for merge, qa: Can't merge

#758 Fixes #17874: Add support of Ubuntu 20 in doc
  src/reference/modules/installation/pages/operating_systems.adoc
Labels: Ready for merge, Trigger test

#768 Fixes #17947: Document how to enable/upgrade plugins after rudder upgrade
  src/reference/modules/installation/pages/upgrade/notes.adoc
Labels: qa: Can't merge

#769 Fixes #18024: Optimize images in the doc
  src/get-started/modules/ROOT/assets/images/technique_editor_add_generic_method.png
  src/get-started/modules/ROOT/assets/images/technique_editor_filter.png
  src/get-started/modules/ROOT/assets/images/technique_editor_first_technique_created.png
  src/get-started/modules/ROOT/assets/images/technique_editor_save.png
  src/get-started/modules/ROOT/assets/images/technique_editor_steps.png
  src/get-started/modules/ROOT/assets/images/trigger-agent-run.png
  src/reference/modules/usage/assets/images/Node_settings.png
  src/reference/modules/usage/assets/images/Rule_compliance.png
  src/reference/modules/usage/assets/images/Rule_management.png
  src/reference/modules/usage/assets/images/event_log.png
  src/reference/modules/usage/assets/images/generic-method-condition-os.png
  src/reference/modules/usage/assets/images/generic-method-result-class.png
  src/reference/modules/usage/assets/images/groups.png
  src/reference/modules/usage/assets/images/node-compliance.png
  src/reference/modules/usage/assets/images/node-lifecycle-nodelist.png
  src/reference/modules/usage/assets/images/node-lifecycle-settings.png
  src/reference/modules/usage/assets/images/node-properties-hierarchy.png
  src/reference/modules/usage/assets/images/nodes.png
  src/reference/modules/usage/assets/images/rudder-admin-settings.png
  src/reference/modules/usage/assets/images/rudder-home.png
  src/reference/modules/usage/assets/images/rudder-quicksearch.png
  src/reference/modules/usage/assets/images/rudder-rule-compliance.png
  src/reference/modules/usage/assets/images/technique_editor/1-rudder-technique-editor-open.png
  src/reference/modules/usage/assets/images/technique_editor/1-rudder-technique-editor.png
  src/reference/modules/usage/assets/images/technique_editor/2-list-techniques.png
  src/reference/modules/usage/assets/images/technique_editor/3-ntp-configuration.png
  src/reference/modules/usage/assets/images/technique_editor/4-list-generics-method.png
  src/reference/modules/usage/assets/images/technique_editor/5-configure-generic-method.png
  src/reference/modules/usage/assets/images/technique_editor/rudder-technique-editor-filter.png
  src/reference/modules/usage/assets/images/technique_editor/technique-editor-parameters.png
  src/reference/modules/usage/assets/images/technique_editor/technique-parameters-ntp.png
  src/reference/modules/usage/assets/images/technique_editor/technique-resource-added.png
  src/reference/modules/usage/assets/images/technique_editor/technique-resource-usage.png
  src/reference/modules/usage/assets/images/technique_editor/technique-resources.png
  src/reference/modules/usage/assets/images/technique_editor/technique-upload-resource.png
  src/reference/modules/usage/assets/images/technique_editor/technique-uploaded-file.png
  src/reference/modules/usage/assets/images/view-property-inheritance.png
  src/rudder-by-example/modules/ROOT/assets/images/git-update.png
  src/rudder-by-example/modules/ROOT/assets/images/nginx.conf.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-configure-repo.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-create-technique.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-directive.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-package-present.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-reports-no-change.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-reports-with-repair.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-rm-cache-condition.png
  src/rudder-by-example/modules/ROOT/assets/images/update-agent-rm-cache-definition.png
Labels: Ready for merge

#771 Fixes #18056: Fix doc build after nodejs upgrade
  rudder-theme/package.json
Labels: Ready for merge

#773 Fixes #18061: Add a rudder by example for group properties
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-all-categories.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-all-nodes.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-dc1-node-property.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-global-param-definition.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-global-param-inherited.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-new-category.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-new-group-dc1-criteria.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-new-group-dc1.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-new-group-debian-criteria.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-new-group-debian10-criteria.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-overriding-conflict-resolution-node.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-overriding-conflict-resolution.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-overriding-conflict.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-prop-dns-debian.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-prop-pkg-config-debian.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-prop-pkg-config-inherited.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-prop-pkg-config-overridden-node.png
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-prop-pkg-config-overridden.png
  src/rudder-by-example/modules/ROOT/assets/images/node-properties-hierarchy.png
  src/rudder-by-example/modules/ROOT/pages/policies/hierarchical-variable-conflict-resolution.adoc
Labels: Ready for merge

#772 Fixes #18055: http in place of https in install doc for zypper subscription repo
  src/reference/modules/installation/pages/_partials/rhel_repo.adoc
  src/reference/modules/installation/pages/_partials/sles_repo.adoc
Labels: Ready for merge, qa: Can't merge

#770 Fixes #18041: Add DSC based node in the network flow schema in the documentation
  src/reference/modules/installation/pages/requirements.adoc
Labels: Ready for merge, qa: Can't merge

#775 Fixes #18074: Add a rudder-by-example for post-provisionning reboot
  rudder-theme/yarn.lock
  src/rudder-by-example/modules/ROOT/assets/images/enabled_group.png
  src/rudder-by-example/modules/ROOT/assets/images/initializing.png
  src/rudder-by-example/modules/ROOT/assets/images/reboot_once.png
  src/rudder-by-example/modules/ROOT/nav.adoc
  src/rudder-by-example/modules/ROOT/pages/policies/reboot-provisioning.adoc
Labels: Ready for merge

#776 Fixes #18079: Missing menu entry towards group properties
  src/rudder-by-example/modules/ROOT/assets/images/hierarchical-variables-node-properties-hierarchy.png
  src/rudder-by-example/modules/ROOT/nav.adoc
  src/rudder-by-example/modules/ROOT/pages/policies/hierarchical-variable-conflict-resolution.adoc
Labels: Ready for merge, qa: Can't merge

#777 Fixes #18080: Update links to ansible inventory plugin
  src/reference/modules/administration/pages/integration.adoc
Labels: Ready for merge
