Repository Normation/rudder-doc, pull requests merged in 2020-09, with the labels that each got.

#767 Fixes #17982: The documentation should mention more obviously that upgrades from 4.3 to 6.0 are not supported
  src/reference/modules/installation/pages/upgrade/notes.adoc
Labels: qa: Can't merge

#763 Fixes #17903: Improve policy ordering doc
  src/reference/modules/usage/pages/advanced_configuration_management.adoc
Labels: Ready for merge, Trigger test, qa: Can't merge

#787 Fixes #18212: Unclear upgrade nodes about 5.0.16+
  src/reference/modules/installation/pages/upgrade/notes.adoc
Labels: Ready for merge

#788 Fixes #18214: Document that JDK 15 is not supported because of nashorn removing
  src/reference/modules/installation/nav.adoc.src
  src/reference/modules/installation/pages/requirements.adoc
Labels: Ready for merge

#786 Fixes #18173: Missing menu link to "contribute"
  src/reference/modules/reference/nav.list
Labels: Ready for merge

#790 Fixes #18223: Add a page for technical stack doc
  src/reference/modules/ROOT/assets/images/tech_stack/curl.svg
  src/reference/modules/ROOT/assets/images/tech_stack/httpd.svg
  src/reference/modules/ROOT/assets/images/tech_stack/rust.svg
  src/reference/modules/ROOT/assets/images/tech_stack/scala.svg
  src/reference/modules/ROOT/nav.list
  src/reference/modules/ROOT/pages/architecture_and_dependencies.adoc
  src/reference/modules/ROOT/pages/technical_stack.adoc
Labels: Trigger test, qa: Can't merge
