Repository Normation/rudder-doc, pull requests merged in 2020-10, with the labels that each got.

#789 Fixes #18190: Add agent-server troubleshooting section
  rudder-theme/src/partials/header-content.hbs
  rudder-theme/yarn.lock
  src/get-started/modules/ROOT/pages/next.adoc
  src/reference/modules/administration/nav.list
  src/reference/modules/administration/pages/troubleshooting.adoc
  src/reference/modules/reference/nav.list
  src/reference/modules/reference/pages/faq.adoc
Labels: Trigger test, qa: Can't merge

#792 Fixes #18373: Error when building dev site
  site-dev.yml
Labels: Ready for merge

#762 Fixes #17803: Advise to not desinstall rudder server if possible
  src/reference/modules/administration/pages/uninstall.adoc
Labels: Ready for merge

#794 Fixes #18350: Document Health Check in user doc
  src/reference/modules/administration/assets/images/healthcheck-ok.png
  src/reference/modules/administration/pages/server.adoc
Labels: Ready for merge, Trigger test

#796 Fixes #18427: USEMETHODREPORTING in metadata documentation is missing
  src/reference/modules/reference/pages/techniques.adoc
Labels: Ready for merge, qa: Can't merge
