Repository Normation/rudder-doc, pull requests merged in 2020-06, with the labels that each got.

#736 Fixes #17751: broken doc build because of spaces in file name
  src/rudder-by-example/modules/ROOT/nav.adoc
  src/rudder-by-example/modules/ROOT/pages/system/update-rudder-agent-package.adoc
Labels: Ready for merge

#739 Fixes #17762: Typos in directive documentation
  src/get-started/modules/ROOT/pages/configuration-policies/directive.adoc
Labels: Ready for merge

#738 Fixes #17760: Typos in technique editor documentation
  src/get-started/modules/ROOT/pages/configuration-policies/technique.adoc
  src/reference/modules/usage/pages/technique_editor.adoc
Labels: Ready for merge

#737 Fixes #17746: Refresh screenshots for technique editor
  src/reference/modules/usage/assets/images/generic-method-condition-os.png
  src/reference/modules/usage/assets/images/generic-method-result-class.png
  src/reference/modules/usage/assets/images/technique_editor/1-rudder-technique-editor-open.png
  src/reference/modules/usage/assets/images/technique_editor/1-rudder-technique-editor.png
  src/reference/modules/usage/assets/images/technique_editor/2-list-techniques.png
  src/reference/modules/usage/assets/images/technique_editor/3-ntp-configuration.png
  src/reference/modules/usage/assets/images/technique_editor/4-list-generics-method.png
  src/reference/modules/usage/assets/images/technique_editor/rudder-technique-editor-filter.png
  src/reference/modules/usage/pages/technique_editor.adoc
Labels: Ready for merge

#744 Fixes #17790: Missing uninstall doc for agent
  src/reference/modules/administration/nav.list
  src/reference/modules/administration/pages/uninstall.adoc
Labels: qa: Can't merge

#751 Fixes #17837: Missing doc about root-relay communication flows
  src/reference/modules/installation/pages/requirements.adoc
Labels: qa: Can't merge

#753 Fixes #17839: remove pg_repack from documentation
  src/reference/modules/administration/pages/procedures.adoc
Labels: qa: Can't merge

#754 Fixes #17840: Add a rudder-by-example for git sync in shared-files
  src/rudder-by-example/modules/ROOT/assets/images/git-update.png
  src/rudder-by-example/modules/ROOT/assets/images/nginx.conf.png
  src/rudder-by-example/modules/ROOT/nav.adoc
  src/rudder-by-example/modules/ROOT/pages/policies/sync-git-repository.adoc
Labels: Ready for merge

#755 Fixes #17834: Improve documentation about communication security
  src/reference/modules/administration/nav.list
  src/reference/modules/administration/pages/security.adoc
Labels: Ready for merge, qa: Can't merge

#756 Fixes #17855: Add trigger agent run feature from UI in get started
  src/get-started/modules/ROOT/assets/images/trigger-agent-run.png
  src/get-started/modules/ROOT/pages/advanced-configuration/compliance.adoc
Labels: Ready for merge

#760 Fixes #17880: Add doc about network resiliency
  src/reference/modules/administration/pages/server.adoc
Labels: Ready for merge, qa: Can't merge
