Repository Normation/rudder-doc, pull requests merged in 2021-06, with the labels that each got.

#828 Fixes #19360: Add ci check for typos in docs
  Jenkinsfile
  src/reference/dependencies/tools/ncf_doc_rudder.py
  src/reference/modules/administration/pages/server.adoc
  src/reference/modules/installation/pages/requirements.adoc
  src/reference/modules/installation/pages/upgrade/notes.adoc
  src/reference/modules/reference/pages/architecture.adoc
  src/reference/modules/reference/pages/jetty_server_configuration.adoc
  src/reference/modules/reference/pages/logs.adoc
  src/reference/modules/reference/pages/techniques.adoc
  src/reference/modules/usage/pages/advanced_configuration_management.adoc
  src/reference/modules/usage/pages/advanced_node_management.adoc
  src/rudder-by-example/modules/ROOT/pages/extending-rudder/add-new-methods.adoc
  src/rudder-by-example/modules/ROOT/pages/policies/using-secrets-in-configuration-policies.adoc
Labels: Trigger test, qa: Can't merge

#829 Fixes #19361: Add ci check for typos in docs - master
  src/rudder-by-example/modules/ROOT/pages/policies/reboot-provisioning.adoc
Labels: Trigger test

#830 Fixes #19420: Update Ansible integration link to Rudder inventory script
  src/reference/modules/administration/pages/integration.adoc
Labels: Trigger test

#831 Fixes #19437: Fix docs about HTTPS reporting in non-compliant mode
  src/reference/modules/administration/pages/server.adoc
  src/reference/modules/installation/pages/upgrade/notes.adoc
Labels: Trigger test, qa: Can't merge

#833 Fixes #19462: Missing doc about methods ordering
  src/reference/modules/usage/pages/advanced_configuration_management.adoc
Labels: Trigger test

#836 Fixes #19493: Remove wrong doc about services passwords
  src/reference/modules/administration/pages/procedures.adoc
Labels: Ready for merge, Trigger test

#837 Fixes #19494: Outdated doc for setting limit of open files for the webapp
  src/reference/modules/administration/pages/performance.adoc
Labels: Trigger test, qa: Can't merge
