Repository Normation/rudder-doc, pull requests merged in 2021-11, with the labels that each got.

#849 Fixes #19919: Document that escaping is incoherent with the rest in Technique Editor in 6.X, that it is corrected in 7.0, and that's a breaking change
  src/reference/modules/usage/pages/configuration_management.adoc
Labels: Ready for merge, Trigger test

#862 Fixes #20220: Add support for Alma and Rocky Linux
  src/reference/modules/installation/pages/operating_systems.adoc
Labels: Trigger test

#864 Fixes #20234: Documentation about collection access in jinja2 template is incorect
  src/reference/modules/usage/pages/variables.adoc
Labels: Trigger test

#866 Fixes #20265: Document windows update technique
  src/rudder-by-example/modules/ROOT/nav.adoc
  src/rudder-by-example/modules/ROOT/pages/system/system-update.adoc
Labels: Trigger test

#853 Fixes #20125: Update supported platform list in documentation
  src/reference/modules/installation/pages/operating_systems.adoc
Labels: qa: Can't merge, Trigger test
