Repository Normation/rudder-doc, pull requests merged in 2022-03, with the labels that each got.

#889 Fixes #20847: Prepare 7.1 doc - borken build
  7.1.yml
  Makefile
  site-dev.yml
  site.yml
  src/changelogs/antora.yml
  src/changelogs/dependencies/Makefile
  src/reference/antora.yml
  src/reference/dependencies/Makefile
Labels: Trigger test

#888 Fixes #20835: Windows support should be documented as the other agents
  src/reference/modules/installation/nav.adoc.src
  src/reference/modules/installation/pages/agent/windows.adoc
  src/reference/modules/installation/pages/operating_systems.adoc
Labels: qa: Can't merge, Ready for merge, Trigger test

#881 Fixes #20621: Add a compatibilty table for agent relay server in the documentation
  src/reference/modules/installation/pages/_partials/current-agent-compatibility.adoc
  src/reference/modules/installation/pages/_partials/global-agent-compatibility.adoc
  src/reference/modules/installation/pages/upgrade/notes.adoc
Labels: qa: Can't merge, Trigger test

#891 Fixes #20891: Correct doc on windows KB update
  src/rudder-by-example/modules/ROOT/pages/system/system-update.adoc
Labels: Ready for merge, Trigger test

#890 Fixes #20888: backup/restore doc is incomplete
  src/reference/modules/administration/pages/procedures.adoc
Labels: Trigger test

#892 Fixes #20942: Broken list of compatible OS in 7.0
  src/reference/modules/installation/pages/operating_systems.adoc
Labels: Trigger test

#893 Fixes #20945: Prepare doc for 7.1
  rudder-theme/src/partials/navigation-explore.hbs
  site.yml
  src/reference/modules/installation/pages/_partials/debian_repo.adoc
  src/reference/modules/installation/pages/_partials/rhel_repo.adoc
  src/reference/modules/installation/pages/_partials/sles_repo.adoc
  src/reference/modules/installation/pages/upgrade/notes.adoc
Labels: Trigger test
